version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 559050230964.dkr.ecr.ap-southeast-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t watermelon-game-backend .
      - docker tag watermelon-game-backend:latest 559050230964.dkr.ecr.ap-southeast-2.amazonaws.com/watermelon-game-backend:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 559050230964.dkr.ecr.ap-southeast-2.amazonaws.com/watermelon-game-backend:latest

artifacts:
  files:
    - '**/*'
